### ISSUE TITLE
file existence disclosure using svg renderer

### ISSUE THREAD

**Issue by bufferoverflow** [blockdiag/blockdiag#147]
Using the **svg renderer**, file existence can be disclosed. This is especially relevant if running blockdiag on a server.

e.g.

```
blockdiag {
A [label = "not exists", background="/etc/test"];
B [label = "exists", background="/etc/passwd"];
}
```

does show:
<img width="805" alt="Screenshot 2021-08-16 at 17 07 51" src="https://user-images.githubusercontent.com/378909/129589347-ba7007b5-0f4b-47f6-888f-cb2e77829578.png">

Relevant code in https://github.com/blockdiag/blockdiag/blob/master/src/blockdiag/imagedraw/svg.py#L250

**Comment by nejch** [comment]
@tk0miya would you accept PRs for this? There's not much activity in this repo so just wanted to check first if you still have time to maintain this.
