### ISSUE TITLE
Add setting for diagram background color

### ISSUE THREAD

**Issue by tk0miya** [blockdiag/blockdiag#41]
Currently it appears to be only possible to set the background color for nodes. It would be nice to be able to set the background color of the image itself. This is particularly helpful when the image is to be embedded elsewhere and where the normally-transparent background does not render properly (e.g. the blurry drop-shadows don't look good when overlaid on a color background).

----------------------------------------
- Bitbucket: https://bitbucket.org/blockdiag/blockdiag/issue/35
- Originally reported by: Ramon Felciano
- Originally created at: 2012-08-24T21:10:37.304

**Comment by tk0miya** [comment]
_From Takeshi KOMIYA on 2012-08-25 02:18:06+00:00_

blockdiag has --no-transparency option to disable transparency of background.
With --no-tranparency option, you will get diagrams with white background.

Do you want to change non-white background?

**Comment by tk0miya** [comment]
_From Ramon Felciano on 2012-08-27 19:31:43+00:00_

I wasn't aware of that option -- that is definitely a good start. However some of our pages are on a grey or black background, and if you use the group {} feature to give each group a distinct fuzzy background color then those fuzzy edges don't look good when transparent on a colored background. So I would consider this still an open feature request, albeit perhaps lower priority since that commandline flag already exists.

**Comment by talwrii** [comment]
For the benefit of google: 

I ran into this problem when using ob-blockdiag in emacs with org-mode. Since I use a black background, my diagram was completely invisible.  I'm fixing this by patching ob-blockdiag.
