### ISSUE TITLE
block diag doesn't work when used in a pyinstaller built program

### ISSUE THREAD

**Issue by tk0miya** [blockdiag/blockdiag#58]
because of the use of setuptools for locating the various image modules (png, jpg), an application built with pyinstaller fails to create images from the diagrams drawn.

----------------------------------------
- Bitbucket: https://bitbucket.org/blockdiag/blockdiag/issue/52
- Originally reported by: Anonymous
- Originally created at: 2014-04-08T21:30:22.033

**Comment by tk0miya** [comment]
_From Takeshi KOMIYA on 2014-04-25 07:56:40+00:00_


What can I do to support pyinstaller?

blockdiag uses setuptools to implement pluggable interface.
And default image drawer modules and shapes are implemented as plug-in.

If you have any idea for coexistence pyinstaller and pluggable interface,
please let me know.

Thanks.

**Comment by tk0miya** [comment]
_From Takeshi KOMIYA on 2014-05-09 10:03:50+00:00_

At blockdiag-discuss list, I've seen simliar post.
https://groups.google.com/forum/#!topic/blockdiag-discuss/9rUQwZXay0k

In this case, he uses cx_freeze to build binary.
but the initialization script will help you.

thanks.

**Comment by tk0miya** [comment]
_From Takeshi KOMIYA on 2014-06-12 14:07:32+00:00_

this issue will be resolved by initializer script.
if you have any problem with this, please reopen.

Thanks

**Comment by ggrossetie** [comment]
@tk0miya Hello and thanks for this great project. I'm also looking for a solution to build a statically linked binary of blockdiag, actdiag, nwdiag and seqdiag. 

> this issue will be resolved by initializer script.
if you have any problem with this, please reopen.

Is there any documentation of how do it ?
I've tried several tools `cx_freeze`, `pyinstaller` with Python 2 and Python 3 but so far no luck :disappointed: 

Thanks!
