### ISSUE TITLE
Switch to git?

### ISSUE THREAD

**Issue by tk0miya** [blockdiag/blockdiag#86]
Most people use that rather than mercurial. That would probably make it easier for people to contribute pull requests.

----------------------------------------
- Bitbucket: https://bitbucket.org/blockdiag/blockdiag/issue/80
- Originally reported by: Petri Savolainen
- Originally created at: 2016-08-31T11:15:39.650

**Comment by tk0miya** [comment]
_From Takeshi KOMIYA on 2016-08-31 15:33:59+00:00_

Agreed. But I don't have time to migrate now.
I will do it later

**Comment by tk0miya** [comment]
_From Anonymous on 2016-09-08 19:31:41+00:00_

Two questions related to this...

1. Do you plan to remain on Bitbucket and/or use another site (like Github or Gitlab)
2. Would you like help in migrating?

**Comment by tk0miya** [comment]
_From Takeshi KOMIYA on 2016-09-16 04:30:20+00:00_

1. I'd like to do that, but not planned.

2. We should consider following things before migrating:

* how to migrate issues and PRs on bitbucket
* Update CI scripts

If you know good tools, please let me know.

**Comment by tk0miya** [comment]
_From [halwine](https://bitbucket.org/halwine) on 2016-10-11 00:34:14+00:00_

The big challenge with migrating issues and PR's is deciding if you want to modify all existing hg hashes to point to the equivalent hashes in the new git repo. If not, then there is a writeup on [moving Bitbucket issues & wiki](http://devblog.ronoaldo.net/2015/08/migrating-bitbucket-mercurial-project-to-git.html) in addition to the code conversion.

That said, I've noticed many folks conflate 'git' with 'GitHub' -- I wouldn't be surprised if the "bigger" barrier is Bitbucket vs GitHub. In which case, I don't believe there is any convenient way to maintain non-code history (issues, PRs, wiki...).

**Comment by bjornfor** [comment]
So I was just looking for the proper blockdiag VCS tree. I thought this tree was it, but it apparently lacks that latest release (v1.5.4). I see this issue mentions https://bitbucket.org/blockdiag/blockdiag/issue/80, so I go there, register for an account, but even after that I'm greeted with "Access denied". Is blockdiag is not doing open development?!

**Comment by bjornfor** [comment]
Oh, so apparently I'm allowed access to https://bitbucket.org/blockdiag/blockdiag/ (but not ".../issues"). And there I see

```
  *IMPORTANT*: This repository was moved to github: https://github.com/blockdiag/blockdiag
```

So I guess that's one more +1 for https://github.com/blockdiag/blockdiag/issues/95 ("Missing git tag for 1.5.4 release"), since _this_ apparently is the main repo now.

**Comment by bjornfor** [comment]
Haha, now I see that this conversation, up to when I started posting, has been imported from bitbucket.org :-)

**Comment by tk0miya** [comment]
Oh, this was already done. Closing.
