### ISSUE TITLE
Missing git tag for 1.5.4 release

### ISSUE THREAD

**Issue by felixonmars** [blockdiag/blockdiag#95]
It would be nice to keep PyPI releases and git tags in sync :)

**Comment by bjornfor** [comment]
Yes please. I'm currently looking for the changelog between 1.5.3 and 1.5.4.

**Comment by tk0miya** [comment]
Sorry for inconvenience.
I just tagged: https://github.com/blockdiag/blockdiag/tree/1.5.4

**Comment by bjornfor** [comment]
Thanks!

**Comment by bjornfor** [comment]
I noticed that there is no branch that contains the new tag. It looks a bit "dangling" at the moment. Perhaps the tag should be merged into master branch? (That's a fast-forward operation.)
